# Generated by Django 5.0.6 on 2024-07-07 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='service',
        ),
        migrations.AlterField(
            model_name='activities',
            name='status',
            field=models.CharField(choices=[('DONE', 'Finished'), ('PEND', 'Pending'), ('UNDO', 'Undone')], max_length=4),
        ),
    ]
